@startuml
set separator none
title ShopSphere

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("ShopSphere.ShopSphere_boundary", "ShopSphere", $tags="") {
  Component(ShopSphere.ShopSphere.Common, "Common", $techn="Module", $descr="", $tags="", $link="")
  Component(ShopSphere.ShopSphere.Ordering, "Ordering", $techn="Module", $descr="", $tags="", $link="")
  Component(ShopSphere.ShopSphere.Catalog, "Catalog", $techn="Module", $descr="", $tags="", $link="")
  Component(ShopSphere.ShopSphere.Identity, "Identity", $techn="Module", $descr="", $tags="", $link="")
  Component(ShopSphere.ShopSphere.Payment, "Payment", $techn="Module", $descr="", $tags="", $link="")
}

Rel(ShopSphere.ShopSphere.Ordering, ShopSphere.ShopSphere.Catalog, "uses", $techn="", $tags="", $link="")
Rel(ShopSphere.ShopSphere.Payment, ShopSphere.ShopSphere.Common, "depends on", $techn="", $tags="", $link="")
Rel(ShopSphere.ShopSphere.Catalog, ShopSphere.ShopSphere.Common, "depends on", $techn="", $tags="", $link="")
Rel(ShopSphere.ShopSphere.Ordering, ShopSphere.ShopSphere.Identity, "depends on", $techn="", $tags="", $link="")
Rel(ShopSphere.ShopSphere.Ordering, ShopSphere.ShopSphere.Common, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml